export enum Role {
  CLIENT = 'CLIENT',
  CINEMA_STAFF = 'CINEMA_STAFF',
  CINEMA_MANAGER = 'CINEMA_MANAGER',
  CINEMA_ADMIN = 'CINEMA_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export class User {
  constructor(
    public readonly id: string,
    public readonly email: string,
    public readonly password: string,
    public readonly firstName: string | null,
    public readonly lastName: string | null,
    public readonly role: Role,
    public readonly cinemaId: string | null,
    public readonly isActive: boolean,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}

  static create(
    email: string,
    password: string,
    firstName?: string,
    lastName?: string,
    role: Role = Role.CLIENT,
    cinemaId?: string,
  ): User {
    return new User(
      '', // Will be generated by DB
      email,
      password,
      firstName || null,
      lastName || null,
      role,
      cinemaId || null,
      true,
      new Date(),
      new Date(),
    );
  }

  withoutPassword() {
    const { password, ...userWithoutPassword } = this;
    return userWithoutPassword as Omit<User, 'password'>;
  }
}
